output_dir: "."

---
title: "RNotebookExample"
output: html_document
---

# This is a heading, not a comment

```{r load-data, message=FALSE}
# Load tidyverse and other packages
library(tidyverse)
library(kableExtra) # used for kbl()
library(rmarkdown) # used for paged_table
library(ggpubr) # used for ggarrange in publications
# read file  into R
pop_data <- read_csv("data/gapminder_data.csv")

# create a table with data from European countries in 2007 - ordered by life expectancy
euro_data_tbl <- pop_data %>% 
  filter(continent == "Europe" & year == 2007) %>% 
  select(-continent, -year) %>% 
  arrange(desc(lifeExp)) %>% 
  rename(Country = country, "Population Size" = pop, "Life Expectancy" = lifeExp, "GDP" = gdpPercap)

```

The results in euro_data_tbl are displayed in the table below:

```{r kbl-table}
euro_data_tbl %>% 
  kbl() %>% 
  kable_styling(bootstrap_options = c("striped", full_width = F)) %>% 
  scroll_box(width = "100%", height = "200px")


```

this is a better way to display long tables

```{r paged-table}
paged_table(euro_data_tbl)
```

# Adding images
```{r images}
euro_data_fig <- pop_data %>% 
  filter(continent == "Europe") %>% 
  mutate(year=as_factor(year))
euro_plot <-  ggplot(data = euro_data_fig, aes(x = year, y = lifeExp)) +
  geom_violin()
   #stat_summary(fun.y = median, geom = "point")
   
# draw euro_plot
euro_plot

```

```{r images 2}
#keep only UK data
uk_data_fig <-  pop_data %>% 
  filter(country == "United Kingdom") %>% 
  mutate(year=as_factor(year))
#UK plot
uk_plot <-  ggplot(data = uk_data_fig, aes(x = year, y = lifeExp)) +
  geom_point()
```

Now we will display more than one images together

```{r fig-comp}

#plot UK and EU plots together
ggarrange(euro_plot, uk_plot, ncol = 2, nrow = 1, labels = "AUTO")

```


